# TODO: Clean up metadata. https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
name: 'Swift Prepare'
author: 'Brian Drelling'
description: 'Prepares a test matrix for the Swift Test workflow.'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  platforms:
    description: 'A comma-delimited list of Swift-compatible platforms to test on.'
    required: false
    default: 'iOS,macOS,tvOS,watchOS,Linux'
  minimum-swift-version:
    description: 'The minimum Swift version to test for. Only supports MAJOR.MINOR syntax (eg. 5.5, not 5.5.1).'
    required: false
    default: '5.3'
outputs:
  test-matrix:
    description: 'A test matrix compatible with the Swift Test workflow.'
    value: ${{ steps.get-test-matrix.outputs.matrix }}
runs:
  using: 'composite'
  steps:
    - name: Get Test Matrix
      id: get-test-matrix
      run: scripts/get_test_matrix.sh ${{ inputs.minimum-swift-version }} ${{ inputs.platforms }}
      shell: bash
      working-directory: ${{ github.action_path }}
