name: Debug

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  swift_test:
    uses: ./.github/workflows/swift_test.yml
    secrets: inherit
    with:
      platforms: macOS Linux
      swift-versions: 5.4 5.6
