name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'Plugins/**'
      - 'Snippets/**'
      - 'Sources/**'
      - 'Tests/**'
      - '**.swift'
      - '**.resolved'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'Plugins/**'
      - 'Snippets/**'
      - 'Sources/**'
      - 'Tests/**'
      - '**.swift'
      - '**.resolved'

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test_vapor_package.yml@main
    secrets: inherit
    with:
      scheme: MyModule
  follow_up:
    runs-on: ubuntu-latest
    needs: [swift_test]
    steps:
      - name: needs
        run: echo ${{ toJSON(needs) }}
      - run: echo ${{ toJSON(needs.swift_test) }}
      - run: echo ${{ toJSON(needs.swift_test.outputs) }}
      - run: echo ${{ needs.swift_test.result }}
  # swift_test:
  #   uses: bdrelling/ci/.github/workflows/swift_test_universal_package_5_3.yml@main
  #   secrets: inherit
  #   with:
  #     scheme: MyModule
